### ISSUE TITLE
.envの位置問題

### ISSUE THREAD

**Issue by gilmiwired** [gilmiwired/randuraft#98]

**Comment by yokoyama443** [comment]
pubspec.yamlのassetsというところに .envという項目を追加するとうまくいくかもわかりません。

flutter:
  assets:
    - assets/images/
    - .env

**Comment by gilmiwired** [comment]
.envをアセットから呼び出そうとしてるがないよ云々みたいなエラーだったから確かにそれでいけるね
んん〜〜〜これいつからこうなったのか今までビルドできてたのに
もしできたらyamlに追加して動作確認した上でPR出してくれると嬉しいです！

**Comment by gilmiwired** [comment]
@yokoyama443

**Comment by gilmiwired** [comment]
ちょっと今スマホしかないので
エラーメッセージか状況のスクショとかあるとうれしい！
難しかったらこっちで確認します！

**Comment by yokoyama443** [comment]
正常に動作しました
今からPR出します
<img width="269" alt="image" src="https://github.com/gilmiwired/randuraft/assets/103204303/203abfce-b8fd-4781-85c9-89dca7596b40">
<img width="248" alt="image" src="https://github.com/gilmiwired/randuraft/assets/103204303/0f0e8168-1b38-46bc-a9dd-deaab0f9ce52">
<img width="834" alt="image" src="https://github.com/gilmiwired/randuraft/assets/103204303/d89dba8b-dd79-449e-b4d4-22596e5ec675">

**Comment by gilmiwired** [comment]
ありがと
あったらでいいけどエラー起きた時のログ見たいかも

**Comment by yokoyama443** [comment]
エラーログです
<img width="1258" alt="image" src="https://github.com/gilmiwired/randuraft/assets/103204303/4d94ea25-e329-4eb8-b122-b8b2c8274eb3">
` Error while trying to load an asset: Flutter Web engine failed to fetch "assets/.env". HTTP request succeeded, but the server responded with HTTP status 404. `

**Comment by gilmiwired** [comment]
素晴らしい

**Comment by yokoyama443** [comment]
とりあえず、PR出したいと思います
